version: '3'

services:
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 chat_service.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=chat_service.settings
    depends_on:
      - redis
      - mongo

  redis:
    image: "redis:latest"

  mongo:
    image: "mongo:latest"
